version: '3.2'
services:
  zk:
    image: "matterlabs/zk-environment:latest"
    command: tail -f /dev/null
    volumes:
      - ${GITHUB_WORKSPACE}:/usr/src/zksync
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
    working_dir: /usr/src/zksync
    environment:
      - IN_DOCKER=true
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
    # secrets:
    #   - host_ssh_key
# secrets:
#   host_ssh_key:
#     file: ~/.ssh/id_rsa

#docker run --volume $SSH_AUTH_SOCK:/ssh-agent --env SSH_AUTH_SOCK=/ssh-agent ubuntu ssh-add -l
#docker run -i -t -v $(readlink -f $SSH_AUTH_SOCK):/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent ubuntu /bin/bash
#  $ boot2docker ssh
#  $ docker run -i -t -v $(readlink -f $SSH_AUTH_SOCK):/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent ubuntu /bin/bash