name: back-end

on: [workflow_dispatch, push]

jobs:
  build_llvm:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: 'compiler'

    # git update-index --chmod +x ./scripts/moveFile.sh
    # chmod +x ${GITHUB_WORKSPACE}/compiler/test.sh
    - name: test.sh
      run: |
        pwd
        ls -l
        sh test.sh
      working-directory: compiler

    - name: Downloading the Solidity compiler binaries
      run: |
        mkdir -pv ${HOME}/opt/solc
        wget 'https://github.com/ethereum/solc-bin/raw/gh-pages/linux-amd64/solc-linux-amd64-v0.8.0%2Bcommit.c7dfd78e' --output-document "${HOME}/opt/solc/solc-0.8.0"
        wget 'https://github.com/ethereum/solc-bin/raw/gh-pages/linux-amd64/solc-linux-amd64-v0.8.1%2Bcommit.df193b15' --output-document "${HOME}/opt/solc/solc-0.8.1"
        wget 'https://github.com/ethereum/solc-bin/raw/gh-pages/linux-amd64/solc-linux-amd64-v0.8.2%2Bcommit.661d1103' --output-document "${HOME}/opt/solc/solc-0.8.2"
        wget 'https://github.com/ethereum/solc-bin/raw/gh-pages/linux-amd64/solc-linux-amd64-v0.8.3%2Bcommit.8d00100c' --output-document "${HOME}/opt/solc/solc-0.8.3"
        wget 'https://github.com/ethereum/solc-bin/raw/gh-pages/linux-amd64/solc-linux-amd64-v0.8.4%2Bcommit.c7e474f2' --output-document "${HOME}/opt/solc/solc-0.8.4"
        wget 'https://github.com/ethereum/solc-bin/raw/gh-pages/linux-amd64/solc-linux-amd64-v0.8.5%2Bcommit.a4f2e591' --output-document "${HOME}/opt/solc/solc-0.8.5"
        wget 'https://github.com/ethereum/solc-bin/raw/gh-pages/linux-amd64/solc-linux-amd64-v0.8.6%2Bcommit.11564f7e' --output-document "${HOME}/opt/solc/solc-0.8.6"
        wget 'https://github.com/ethereum/solc-bin/raw/gh-pages/linux-amd64/solc-linux-amd64-v0.8.7%2Bcommit.e28d00a7' --output-document "${HOME}/opt/solc/solc-0.8.7"
        echo ${HOME}/opt/solc >> ${GITHUB_PATH}
    
    - name: Checkout tests
      uses: actions/checkout@v2
      with:
        repository: warsmit-projects/test_cypress
        ref: main
        submodules: true
        token: ${{ secrets.G_ACCESS_TOKEN }}
        path: 'tests'
    
    - name: run test
      run: |
        ls -l ${GITHUB_WORKSPACE}
        ls -l ${GITHUB_WORKSPACE}/tests
        sh ${GITHUB_WORKSPACE}/tests/test.sh
